#!/bin/sh
d="$1"
v=${d%/*}/VERIFICATION.md; { echo '<!-- generated by /potion:verify — hand-editing is a defect; regenerate instead -->'
echo '| File | SHA256-8 | Producer | Truths |'; echo '|---|---|---|---|'
for f in "$d"/*; do n=${f##*/}; [ "$n" = INDEX.md ] && continue
t=$(grep -F "$n" "$v" | sed -n 's/^| *\([0-9][0-9]*\)\..*/\1/p' | sort -un | paste -sd, -)
echo "| $n | $(sha256sum "$f" | cut -c1-8) | ${n%%-*} | ${t:--} |"; done
for f in "$d"/*; do n=${f##*/}; [ "$n" = INDEX.md ] || echo "$(sha256sum "$f" | cut -c1-8) $n"; done \
| sort | awk 'h==$1{print "DUPLICATE: "p" == "$2}{h=$1;p=$2}'; } > "$d"/INDEX.md
